# Generated by Django 3.2.15 on 2022-10-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factCheckUser', models.CharField(max_length=100)),
                ('TwitterHandle', models.CharField(max_length=100)),
                ('TweetId', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
